//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("MarketingData", "FK_CraigsListResponse_CraigslistPosts", "CraigslistPosts", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MarketingData.Implementation.CraigslistPost), "CraigsListResponse", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MarketingData.Implementation.CraigsListResponse), true)]

#endregion

namespace MarketingData.Implementation
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MarketingDataObjectContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MarketingDataObjectContext object using the connection string found in the 'MarketingDataObjectContext' section of the application configuration file.
        /// </summary>
        public MarketingDataObjectContext() : base("name=MarketingDataObjectContext", "MarketingDataObjectContext")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MarketingDataObjectContext object.
        /// </summary>
        public MarketingDataObjectContext(string connectionString) : base(connectionString, "MarketingDataObjectContext")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MarketingDataObjectContext object.
        /// </summary>
        public MarketingDataObjectContext(EntityConnection connection) : base(connection, "MarketingDataObjectContext")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CraigslistPost> CraigslistPosts
        {
            get
            {
                if ((_CraigslistPosts == null))
                {
                    _CraigslistPosts = base.CreateObjectSet<CraigslistPost>("CraigslistPosts");
                }
                return _CraigslistPosts;
            }
        }
        private ObjectSet<CraigslistPost> _CraigslistPosts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CraigsListResponse> CraigsListResponses
        {
            get
            {
                if ((_CraigsListResponses == null))
                {
                    _CraigsListResponses = base.CreateObjectSet<CraigsListResponse>("CraigsListResponses");
                }
                return _CraigsListResponses;
            }
        }
        private ObjectSet<CraigsListResponse> _CraigsListResponses;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CraigslistPosts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCraigslistPosts(CraigslistPost craigslistPost)
        {
            base.AddObject("CraigslistPosts", craigslistPost);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CraigsListResponses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCraigsListResponses(CraigsListResponse craigsListResponse)
        {
            base.AddObject("CraigsListResponses", craigsListResponse);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MarketingData", Name="CraigslistPost")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CraigslistPost : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CraigslistPost object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="postId">Initial value of the PostId property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="emailAddress">Initial value of the EmailAddress property.</param>
        /// <param name="postDate">Initial value of the PostDate property.</param>
        /// <param name="postsElement">Initial value of the PostsElement property.</param>
        public static CraigslistPost CreateCraigslistPost(global::System.Guid id, global::System.Int64 postId, global::System.String title, global::System.String emailAddress, global::System.DateTime postDate, global::System.String postsElement)
        {
            CraigslistPost craigslistPost = new CraigslistPost();
            craigslistPost.Id = id;
            craigslistPost.PostId = postId;
            craigslistPost.Title = title;
            craigslistPost.EmailAddress = emailAddress;
            craigslistPost.PostDate = postDate;
            craigslistPost.PostsElement = postsElement;
            return craigslistPost;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 PostId
        {
            get
            {
                return _PostId;
            }
            set
            {
                OnPostIdChanging(value);
                ReportPropertyChanging("PostId");
                _PostId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PostId");
                OnPostIdChanged();
            }
        }
        private global::System.Int64 _PostId;
        partial void OnPostIdChanging(global::System.Int64 value);
        partial void OnPostIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmailAddress
        {
            get
            {
                return _EmailAddress;
            }
            set
            {
                OnEmailAddressChanging(value);
                ReportPropertyChanging("EmailAddress");
                _EmailAddress = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmailAddress");
                OnEmailAddressChanged();
            }
        }
        private global::System.String _EmailAddress;
        partial void OnEmailAddressChanging(global::System.String value);
        partial void OnEmailAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime PostDate
        {
            get
            {
                return _PostDate;
            }
            set
            {
                OnPostDateChanging(value);
                ReportPropertyChanging("PostDate");
                _PostDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PostDate");
                OnPostDateChanged();
            }
        }
        private global::System.DateTime _PostDate;
        partial void OnPostDateChanging(global::System.DateTime value);
        partial void OnPostDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PostsElement
        {
            get
            {
                return _PostsElement;
            }
            set
            {
                OnPostsElementChanging(value);
                ReportPropertyChanging("PostsElement");
                _PostsElement = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PostsElement");
                OnPostsElementChanged();
            }
        }
        private global::System.String _PostsElement;
        partial void OnPostsElementChanging(global::System.String value);
        partial void OnPostsElementChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MarketingData", "FK_CraigsListResponse_CraigslistPosts", "CraigsListResponse")]
        public EntityCollection<CraigsListResponse> CraigsListResponses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CraigsListResponse>("MarketingData.FK_CraigsListResponse_CraigslistPosts", "CraigsListResponse");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CraigsListResponse>("MarketingData.FK_CraigsListResponse_CraigslistPosts", "CraigsListResponse", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MarketingData", Name="CraigsListResponse")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CraigsListResponse : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CraigsListResponse object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="responseContent">Initial value of the ResponseContent property.</param>
        /// <param name="responseHtmlContent">Initial value of the ResponseHtmlContent property.</param>
        /// <param name="created">Initial value of the Created property.</param>
        /// <param name="craigslitPostsId">Initial value of the CraigslitPostsId property.</param>
        public static CraigsListResponse CreateCraigsListResponse(global::System.Guid id, global::System.String responseContent, global::System.String responseHtmlContent, global::System.DateTime created, global::System.Guid craigslitPostsId)
        {
            CraigsListResponse craigsListResponse = new CraigsListResponse();
            craigsListResponse.Id = id;
            craigsListResponse.ResponseContent = responseContent;
            craigsListResponse.ResponseHtmlContent = responseHtmlContent;
            craigsListResponse.Created = created;
            craigsListResponse.CraigslitPostsId = craigslitPostsId;
            return craigsListResponse;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ResponseContent
        {
            get
            {
                return _ResponseContent;
            }
            set
            {
                OnResponseContentChanging(value);
                ReportPropertyChanging("ResponseContent");
                _ResponseContent = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ResponseContent");
                OnResponseContentChanged();
            }
        }
        private global::System.String _ResponseContent;
        partial void OnResponseContentChanging(global::System.String value);
        partial void OnResponseContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ResponseHtmlContent
        {
            get
            {
                return _ResponseHtmlContent;
            }
            set
            {
                OnResponseHtmlContentChanging(value);
                ReportPropertyChanging("ResponseHtmlContent");
                _ResponseHtmlContent = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ResponseHtmlContent");
                OnResponseHtmlContentChanged();
            }
        }
        private global::System.String _ResponseHtmlContent;
        partial void OnResponseHtmlContentChanging(global::System.String value);
        partial void OnResponseHtmlContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CraigslitPostsId
        {
            get
            {
                return _CraigslitPostsId;
            }
            set
            {
                OnCraigslitPostsIdChanging(value);
                ReportPropertyChanging("CraigslitPostsId");
                _CraigslitPostsId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CraigslitPostsId");
                OnCraigslitPostsIdChanged();
            }
        }
        private global::System.Guid _CraigslitPostsId;
        partial void OnCraigslitPostsIdChanging(global::System.Guid value);
        partial void OnCraigslitPostsIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MarketingData", "FK_CraigsListResponse_CraigslistPosts", "CraigslistPosts")]
        public CraigslistPost CraigslistPost
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CraigslistPost>("MarketingData.FK_CraigsListResponse_CraigslistPosts", "CraigslistPosts").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CraigslistPost>("MarketingData.FK_CraigsListResponse_CraigslistPosts", "CraigslistPosts").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CraigslistPost> CraigslistPostReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CraigslistPost>("MarketingData.FK_CraigsListResponse_CraigslistPosts", "CraigslistPosts");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CraigslistPost>("MarketingData.FK_CraigsListResponse_CraigslistPosts", "CraigslistPosts", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
