

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class CraigslistPostKeyword : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.CraigslistPostKeyword, global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the CraigslistPostKeyword entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public CraigslistPostKeyword()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public CraigslistPostKeyword(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.CraigslistPostKeyword> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CraigslistPostKeyword_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CraigslistPostKeyword_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Guid CraigslistPostId
        {
            get
            {
                return global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.GetValue(this, global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.PropertySetProperties.CraigslistPostId);
            }
            set
            {
                global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.SetValue(this, global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.PropertySetProperties.CraigslistPostId, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CraigslistPostId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CraigslistPostId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CraigslistPostId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Guid KeywordId
        {
            get
            {
                return global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.GetValue(this, global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.PropertySetProperties.KeywordId);
            }
            set
            {
                global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.SetValue(this, global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.PropertySetProperties.KeywordId, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void KeywordId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void KeywordId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void KeywordId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.CraigslistPost CraigslistPost
        {
            get
            {
                return global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.GetValue(this, global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.PropertySetProperties.CraigslistPost);
            }
            set
            {
                global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.SetValue(this, global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.PropertySetProperties.CraigslistPost, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CraigslistPost_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CraigslistPost_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CraigslistPost_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.CraigslistPostKeyword,
                global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass,
                global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.IImplementation,
                global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.CraigslistPostKeyword, global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.CraigslistPostKeyword, global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.PropertySetProperties.CraigslistPostId;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.CraigslistPostKeyword, global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass>.Entry
                __CraigslistPostKeywordEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.CraigslistPostKeyword, global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass>.Entry(
                    global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.__CraigslistPostKeyword_CreateNew,
                    global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.__CraigslistPostKeyword_Created,
                    global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.__CraigslistPostKeyword_AllowSaveWithErrors);
            private static global::LightSwitchApplication.CraigslistPostKeyword __CraigslistPostKeyword_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.CraigslistPostKeyword> es)
            {
                return new global::LightSwitchApplication.CraigslistPostKeyword(es);
            }
            private static void __CraigslistPostKeyword_Created(global::LightSwitchApplication.CraigslistPostKeyword e)
            {
                e.CraigslistPostKeyword_Created();
            }
            private static bool __CraigslistPostKeyword_AllowSaveWithErrors(global::LightSwitchApplication.CraigslistPostKeyword e)
            {
                bool result = false;
                e.CraigslistPostKeyword_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.CraigslistPostKeyword, global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.CraigslistPostKeyword, global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.CraigslistPostKeyword, global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraigslistPostKeyword, global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass, global::System.Guid> CraigslistPostId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.PropertySetProperties.CraigslistPostId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraigslistPostKeyword, global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass, global::System.Guid>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraigslistPostKeyword, global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass, global::System.Guid> KeywordId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.PropertySetProperties.KeywordId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraigslistPostKeyword, global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass, global::System.Guid>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CraigslistPostKeyword, global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass, global::LightSwitchApplication.CraigslistPost> CraigslistPost
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.PropertySetProperties.CraigslistPost) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CraigslistPostKeyword, global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass, global::LightSwitchApplication.CraigslistPost>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new global::System.Guid CraigslistPostId { get; set; }
                new global::System.Guid KeywordId { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation CraigslistPost { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraigslistPostKeyword, global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass, global::System.Guid>.Entry
                    CraigslistPostId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraigslistPostKeyword, global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass, global::System.Guid>.Entry(
                        "CraigslistPostId",
                        global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.PropertySetProperties._CraigslistPostId_Stub,
                        global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.PropertySetProperties._CraigslistPostId_ComputeIsReadOnly,
                        global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.PropertySetProperties._CraigslistPostId_Validate,
                        global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.PropertySetProperties._CraigslistPostId_GetImplementationValue,
                        global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.PropertySetProperties._CraigslistPostId_SetImplementationValue,
                        global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.PropertySetProperties._CraigslistPostId_OnValueChanged);
                private static void _CraigslistPostId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraigslistPostKeyword, global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass, global::System.Guid>.Data> c, global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass d, object sf)
                {
                    c(d, ref d._CraigslistPostId, sf);
                }
                private static bool _CraigslistPostId_ComputeIsReadOnly(global::LightSwitchApplication.CraigslistPostKeyword e)
                {
                    bool result = false;
                    e.CraigslistPostId_IsReadOnly(ref result);
                    return result;
                }
                private static void _CraigslistPostId_Validate(global::LightSwitchApplication.CraigslistPostKeyword e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CraigslistPostId_Validate(r);
                }
                private static global::System.Guid _CraigslistPostId_GetImplementationValue(global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass d)
                {
                    return d.ImplementationEntity.CraigslistPostId;
                }
                private static void _CraigslistPostId_SetImplementationValue(global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass d, global::System.Guid v)
                {
                    d.ImplementationEntity.CraigslistPostId = v;
                }
                private static void _CraigslistPostId_OnValueChanged(global::LightSwitchApplication.CraigslistPostKeyword e)
                {
                    e.CraigslistPostId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraigslistPostKeyword, global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass, global::System.Guid>.Entry
                    KeywordId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraigslistPostKeyword, global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass, global::System.Guid>.Entry(
                        "KeywordId",
                        global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.PropertySetProperties._KeywordId_Stub,
                        global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.PropertySetProperties._KeywordId_ComputeIsReadOnly,
                        global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.PropertySetProperties._KeywordId_Validate,
                        global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.PropertySetProperties._KeywordId_GetImplementationValue,
                        global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.PropertySetProperties._KeywordId_SetImplementationValue,
                        global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.PropertySetProperties._KeywordId_OnValueChanged);
                private static void _KeywordId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraigslistPostKeyword, global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass, global::System.Guid>.Data> c, global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass d, object sf)
                {
                    c(d, ref d._KeywordId, sf);
                }
                private static bool _KeywordId_ComputeIsReadOnly(global::LightSwitchApplication.CraigslistPostKeyword e)
                {
                    bool result = false;
                    e.KeywordId_IsReadOnly(ref result);
                    return result;
                }
                private static void _KeywordId_Validate(global::LightSwitchApplication.CraigslistPostKeyword e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.KeywordId_Validate(r);
                }
                private static global::System.Guid _KeywordId_GetImplementationValue(global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass d)
                {
                    return d.ImplementationEntity.KeywordId;
                }
                private static void _KeywordId_SetImplementationValue(global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass d, global::System.Guid v)
                {
                    d.ImplementationEntity.KeywordId = v;
                }
                private static void _KeywordId_OnValueChanged(global::LightSwitchApplication.CraigslistPostKeyword e)
                {
                    e.KeywordId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CraigslistPostKeyword, global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass, global::LightSwitchApplication.CraigslistPost>.Entry
                    CraigslistPost = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CraigslistPostKeyword, global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass, global::LightSwitchApplication.CraigslistPost>.Entry(
                        "CraigslistPost",
                        global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.PropertySetProperties._CraigslistPost_Stub,
                        global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.PropertySetProperties._CraigslistPost_ComputeIsReadOnly,
                        global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.PropertySetProperties._CraigslistPost_Validate,
                        global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.PropertySetProperties._CraigslistPost_GetCoreImplementationValue,
                        global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.PropertySetProperties._CraigslistPost_GetImplementationValue,
                        global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.PropertySetProperties._CraigslistPost_SetImplementationValue,
                        global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.PropertySetProperties._CraigslistPost_Refresh,
                        global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.PropertySetProperties._CraigslistPost_OnValueChanged);
                private static void _CraigslistPost_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CraigslistPostKeyword, global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass, global::LightSwitchApplication.CraigslistPost>.Data> c, global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass d, object sf)
                {
                    c(d, ref d._CraigslistPost, sf);
                }
                private static bool _CraigslistPost_ComputeIsReadOnly(global::LightSwitchApplication.CraigslistPostKeyword e)
                {
                    bool result = false;
                    e.CraigslistPost_IsReadOnly(ref result);
                    return result;
                }
                private static void _CraigslistPost_Validate(global::LightSwitchApplication.CraigslistPostKeyword e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CraigslistPost_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _CraigslistPost_GetCoreImplementationValue(global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass d)
                {
                    return d.ImplementationEntity.CraigslistPost;
                }
                private static global::LightSwitchApplication.CraigslistPost _CraigslistPost_GetImplementationValue(global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.CraigslistPost, global::LightSwitchApplication.CraigslistPost.DetailsClass>(global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.PropertySetProperties.CraigslistPost, ref d._CraigslistPost);
                }
                private static void _CraigslistPost_SetImplementationValue(global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass d, global::LightSwitchApplication.CraigslistPost v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.PropertySetProperties.CraigslistPost, ref d._CraigslistPost, (i, ev) => i.CraigslistPost = ev, v);
                }
                private static void _CraigslistPost_Refresh(global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass.PropertySetProperties.CraigslistPost, ref d._CraigslistPost);
                }
                private static void _CraigslistPost_OnValueChanged(global::LightSwitchApplication.CraigslistPostKeyword e)
                {
                    e.CraigslistPost_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraigslistPostKeyword, global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass, global::System.Guid>.Data _CraigslistPostId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraigslistPostKeyword, global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass, global::System.Guid>.Data _KeywordId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CraigslistPostKeyword, global::LightSwitchApplication.CraigslistPostKeyword.DetailsClass, global::LightSwitchApplication.CraigslistPost>.Data _CraigslistPost;
            
        }
    
        #endregion
    }
    
    #endregion
}
