

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class Keyword : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Keyword, global::LightSwitchApplication.Keyword.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Keyword entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Keyword()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Keyword(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Keyword> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Keyword.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Keyword_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Keyword_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return global::LightSwitchApplication.Keyword.DetailsClass.GetValue(this, global::LightSwitchApplication.Keyword.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Keyword.DetailsClass.SetValue(this, global::LightSwitchApplication.Keyword.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Keyword1
        {
            get
            {
                return global::LightSwitchApplication.Keyword.DetailsClass.GetValue(this, global::LightSwitchApplication.Keyword.DetailsClass.PropertySetProperties.Keyword1);
            }
            set
            {
                global::LightSwitchApplication.Keyword.DetailsClass.SetValue(this, global::LightSwitchApplication.Keyword.DetailsClass.PropertySetProperties.Keyword1, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Keyword1_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Keyword1_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Keyword1_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Score
        {
            get
            {
                return global::LightSwitchApplication.Keyword.DetailsClass.GetValue(this, global::LightSwitchApplication.Keyword.DetailsClass.PropertySetProperties.Score);
            }
            set
            {
                global::LightSwitchApplication.Keyword.DetailsClass.SetValue(this, global::LightSwitchApplication.Keyword.DetailsClass.PropertySetProperties.Score, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Score_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Score_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Score_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Keyword,
                global::LightSwitchApplication.Keyword.DetailsClass,
                global::LightSwitchApplication.Keyword.DetailsClass.IImplementation,
                global::LightSwitchApplication.Keyword.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Keyword, global::LightSwitchApplication.Keyword.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Keyword, global::LightSwitchApplication.Keyword.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Keyword.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Keyword, global::LightSwitchApplication.Keyword.DetailsClass>.Entry
                __KeywordEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Keyword, global::LightSwitchApplication.Keyword.DetailsClass>.Entry(
                    global::LightSwitchApplication.Keyword.DetailsClass.__Keyword_CreateNew,
                    global::LightSwitchApplication.Keyword.DetailsClass.__Keyword_Created,
                    global::LightSwitchApplication.Keyword.DetailsClass.__Keyword_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Keyword __Keyword_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Keyword> es)
            {
                return new global::LightSwitchApplication.Keyword(es);
            }
            private static void __Keyword_Created(global::LightSwitchApplication.Keyword e)
            {
                e.Keyword_Created();
            }
            private static bool __Keyword_AllowSaveWithErrors(global::LightSwitchApplication.Keyword e)
            {
                bool result = false;
                e.Keyword_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Keyword, global::LightSwitchApplication.Keyword.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Keyword, global::LightSwitchApplication.Keyword.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Keyword.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Keyword, global::LightSwitchApplication.Keyword.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Keyword, global::LightSwitchApplication.Keyword.DetailsClass, global::System.Guid> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Keyword.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Keyword, global::LightSwitchApplication.Keyword.DetailsClass, global::System.Guid>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Keyword, global::LightSwitchApplication.Keyword.DetailsClass, string> Keyword1
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Keyword.DetailsClass.PropertySetProperties.Keyword1) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Keyword, global::LightSwitchApplication.Keyword.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Keyword, global::LightSwitchApplication.Keyword.DetailsClass, int> Score
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Keyword.DetailsClass.PropertySetProperties.Score) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Keyword, global::LightSwitchApplication.Keyword.DetailsClass, int>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new global::System.Guid Id { get; set; }
                new string Keyword1 { get; set; }
                new int Score { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Keyword, global::LightSwitchApplication.Keyword.DetailsClass, global::System.Guid>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Keyword, global::LightSwitchApplication.Keyword.DetailsClass, global::System.Guid>.Entry(
                        "Id",
                        global::LightSwitchApplication.Keyword.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Keyword.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Keyword.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Keyword.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Keyword.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Keyword.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Keyword.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Keyword, global::LightSwitchApplication.Keyword.DetailsClass, global::System.Guid>.Data> c, global::LightSwitchApplication.Keyword.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Keyword e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Keyword e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static global::System.Guid _Id_GetImplementationValue(global::LightSwitchApplication.Keyword.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Keyword.DetailsClass d, global::System.Guid v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Keyword e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Keyword, global::LightSwitchApplication.Keyword.DetailsClass, string>.Entry
                    Keyword1 = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Keyword, global::LightSwitchApplication.Keyword.DetailsClass, string>.Entry(
                        "Keyword1",
                        global::LightSwitchApplication.Keyword.DetailsClass.PropertySetProperties._Keyword1_Stub,
                        global::LightSwitchApplication.Keyword.DetailsClass.PropertySetProperties._Keyword1_ComputeIsReadOnly,
                        global::LightSwitchApplication.Keyword.DetailsClass.PropertySetProperties._Keyword1_Validate,
                        global::LightSwitchApplication.Keyword.DetailsClass.PropertySetProperties._Keyword1_GetImplementationValue,
                        global::LightSwitchApplication.Keyword.DetailsClass.PropertySetProperties._Keyword1_SetImplementationValue,
                        global::LightSwitchApplication.Keyword.DetailsClass.PropertySetProperties._Keyword1_OnValueChanged);
                private static void _Keyword1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Keyword.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Keyword, global::LightSwitchApplication.Keyword.DetailsClass, string>.Data> c, global::LightSwitchApplication.Keyword.DetailsClass d, object sf)
                {
                    c(d, ref d._Keyword1, sf);
                }
                private static bool _Keyword1_ComputeIsReadOnly(global::LightSwitchApplication.Keyword e)
                {
                    bool result = false;
                    e.Keyword1_IsReadOnly(ref result);
                    return result;
                }
                private static void _Keyword1_Validate(global::LightSwitchApplication.Keyword e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Keyword1_Validate(r);
                }
                private static string _Keyword1_GetImplementationValue(global::LightSwitchApplication.Keyword.DetailsClass d)
                {
                    return d.ImplementationEntity.Keyword1;
                }
                private static void _Keyword1_SetImplementationValue(global::LightSwitchApplication.Keyword.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Keyword1 = v;
                }
                private static void _Keyword1_OnValueChanged(global::LightSwitchApplication.Keyword e)
                {
                    e.Keyword1_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Keyword, global::LightSwitchApplication.Keyword.DetailsClass, int>.Entry
                    Score = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Keyword, global::LightSwitchApplication.Keyword.DetailsClass, int>.Entry(
                        "Score",
                        global::LightSwitchApplication.Keyword.DetailsClass.PropertySetProperties._Score_Stub,
                        global::LightSwitchApplication.Keyword.DetailsClass.PropertySetProperties._Score_ComputeIsReadOnly,
                        global::LightSwitchApplication.Keyword.DetailsClass.PropertySetProperties._Score_Validate,
                        global::LightSwitchApplication.Keyword.DetailsClass.PropertySetProperties._Score_GetImplementationValue,
                        global::LightSwitchApplication.Keyword.DetailsClass.PropertySetProperties._Score_SetImplementationValue,
                        global::LightSwitchApplication.Keyword.DetailsClass.PropertySetProperties._Score_OnValueChanged);
                private static void _Score_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Keyword.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Keyword, global::LightSwitchApplication.Keyword.DetailsClass, int>.Data> c, global::LightSwitchApplication.Keyword.DetailsClass d, object sf)
                {
                    c(d, ref d._Score, sf);
                }
                private static bool _Score_ComputeIsReadOnly(global::LightSwitchApplication.Keyword e)
                {
                    bool result = false;
                    e.Score_IsReadOnly(ref result);
                    return result;
                }
                private static void _Score_Validate(global::LightSwitchApplication.Keyword e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Score_Validate(r);
                }
                private static int _Score_GetImplementationValue(global::LightSwitchApplication.Keyword.DetailsClass d)
                {
                    return d.ImplementationEntity.Score;
                }
                private static void _Score_SetImplementationValue(global::LightSwitchApplication.Keyword.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Score = v;
                }
                private static void _Score_OnValueChanged(global::LightSwitchApplication.Keyword e)
                {
                    e.Score_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Keyword, global::LightSwitchApplication.Keyword.DetailsClass, global::System.Guid>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Keyword, global::LightSwitchApplication.Keyword.DetailsClass, string>.Data _Keyword1;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Keyword, global::LightSwitchApplication.Keyword.DetailsClass, int>.Data _Score;
            
        }
    
        #endregion
    }
    
    #endregion
}
