//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class CraigsListPosts
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.CraigsListPosts, global::LightSwitchApplication.CraigsListPosts.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private CraigsListPosts() : base("LightSwitchApplication:CraigsListPosts")
        {
            global::LightSwitchApplication.CraigsListPosts.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static CraigsListPosts CreateInstance()
        {
            return new global::LightSwitchApplication.CraigsListPosts(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CraigsListPosts_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CraigsListPosts_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CraigsListPosts_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CraigsListPosts_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CraigsListPosts_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CraigsListPosts_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CraigsListPosts_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void CraigslistPostsDataSource_SelectionChanged();

        partial void CraigslistPostsDataSource_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CraigslistPostsDataSource_Loaded(bool succeeded);

        /// <summary>
        /// Gets the CraigslistPostsDataSource visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.CraigslistPost> CraigslistPostsDataSource
        {
            get
            {
                return global::LightSwitchApplication.CraigsListPosts.DetailsClass.GetValue(this, global::LightSwitchApplication.CraigsListPosts.DetailsClass.PropertySetProperties.CraigslistPostsDataSource);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CraigslistPostsDataSource_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Calls the CreateNewResponse screen method.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void CreateNewResponse()
        {
            this.Details.Methods.CreateNewResponse.CreateInvocation().Execute();
        }
        partial void CreateNewResponse_CanExecute(ref bool result);
        partial void CreateNewResponse_Execute();

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CraigsListPosts, global::LightSwitchApplication.CraigsListPosts.DetailsClass, global::LightSwitchApplication.CraigsListPosts.DetailsClass.PropertySet, global::LightSwitchApplication.CraigsListPosts.DetailsClass.CommandSet, global::LightSwitchApplication.CraigsListPosts.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.CraigsListPosts.DetailsClass.PropertySetProperties.CraigslistPostsDataSource;
                var initializeCommandEntry = global::LightSwitchApplication.CraigsListPosts.DetailsClass.CommandSetProperties.CreateNewResponse;
                var initializeMethodEntry = global::LightSwitchApplication.CraigsListPosts.DetailsClass.MethodSetProperties.CreateNewResponse;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CraigsListPosts, global::LightSwitchApplication.CraigsListPosts.DetailsClass>.Entry
                __CraigsListPostsEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CraigsListPosts, global::LightSwitchApplication.CraigsListPosts.DetailsClass>.Entry(
                    global::LightSwitchApplication.CraigsListPosts.DetailsClass.__CraigsListPosts_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.CraigsListPosts.DetailsClass.__CraigsListPosts_InvokeSavingEvent,
                    global::LightSwitchApplication.CraigsListPosts.DetailsClass.__CraigsListPosts_InvokeSavedEvent,
                    global::LightSwitchApplication.CraigsListPosts.DetailsClass.__CraigsListPosts_InvokeClosingEvent,
                    global::LightSwitchApplication.CraigsListPosts.DetailsClass.__CraigsListPosts_InvokeCreated,
                    global::LightSwitchApplication.CraigsListPosts.DetailsClass.__CraigsListPosts_InvokeActivated,
                    global::LightSwitchApplication.CraigsListPosts.DetailsClass.__CraigsListPosts_InvokeSaveErrorEvent);
            private static void __CraigsListPosts_InvokeInitializeDataWorkspace(global::LightSwitchApplication.CraigsListPosts s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.CraigsListPosts_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __CraigsListPosts_InvokeSavingEvent(global::LightSwitchApplication.CraigsListPosts s)
            {
                bool handled = false;
                s.CraigsListPosts_Saving(ref handled);
                return handled;
            }
            private static void __CraigsListPosts_InvokeSavedEvent(global::LightSwitchApplication.CraigsListPosts s)
            {
                s.CraigsListPosts_Saved();
            }
            private static bool __CraigsListPosts_InvokeClosingEvent(global::LightSwitchApplication.CraigsListPosts s)
            {
                bool cancel = false;
                s.CraigsListPosts_Closing(ref cancel);
                return cancel;
            }
            private static void __CraigsListPosts_InvokeCreated(global::LightSwitchApplication.CraigsListPosts s)
            {
                s.CraigsListPosts_Created();
            }
            private static void __CraigsListPosts_InvokeActivated(global::LightSwitchApplication.CraigsListPosts s)
            {
                s.CraigsListPosts_Activated();
            }
            private static bool __CraigsListPosts_InvokeSaveErrorEvent(global::LightSwitchApplication.CraigsListPosts s, global::System.Exception ex)
            {
                bool handled = false;
                s.CraigsListPosts_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.CraigsListPosts.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.CraigsListPosts.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.CraigsListPosts.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable CraigslistPostsDataSourceQuery()
            {
                return this.Screen.DataWorkspace.MarketingData.CraigslistPosts;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CraigsListPosts, global::LightSwitchApplication.CraigsListPosts.DetailsClass, global::LightSwitchApplication.CraigslistPost>.Data _CraigslistPostsDataSource;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.CraigsListPosts, global::LightSwitchApplication.CraigsListPosts.DetailsClass>.Data _CreateNewResponseCommand;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.CraigsListPosts, global::LightSwitchApplication.CraigsListPosts.DetailsClass>.Data _CreateNewResponseMethod;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.CraigsListPosts, global::LightSwitchApplication.CraigsListPosts.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CraigsListPosts, global::LightSwitchApplication.CraigsListPosts.DetailsClass, global::LightSwitchApplication.CraigslistPost> CraigslistPostsDataSource
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CraigsListPosts, global::LightSwitchApplication.CraigsListPosts.DetailsClass, global::LightSwitchApplication.CraigslistPost>)base.GetItem(global::LightSwitchApplication.CraigsListPosts.DetailsClass.PropertySetProperties.CraigslistPostsDataSource);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.CraigsListPosts, global::LightSwitchApplication.CraigsListPosts.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.CraigsListPosts, global::LightSwitchApplication.CraigsListPosts.DetailsClass> CreateNewResponse
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.CraigsListPosts, global::LightSwitchApplication.CraigsListPosts.DetailsClass>)base.GetItem(global::LightSwitchApplication.CraigsListPosts.DetailsClass.CommandSetProperties.CreateNewResponse);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.CraigsListPosts, global::LightSwitchApplication.CraigsListPosts.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.CraigsListPosts, global::LightSwitchApplication.CraigsListPosts.DetailsClass> CreateNewResponse
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.CraigsListPosts, global::LightSwitchApplication.CraigsListPosts.DetailsClass>)base.GetItem(global::LightSwitchApplication.CraigsListPosts.DetailsClass.MethodSetProperties.CreateNewResponse);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CraigsListPosts, global::LightSwitchApplication.CraigsListPosts.DetailsClass, global::LightSwitchApplication.CraigslistPost>.Entry
                    CraigslistPostsDataSource = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CraigsListPosts, global::LightSwitchApplication.CraigsListPosts.DetailsClass, global::LightSwitchApplication.CraigslistPost>.Entry(
                        "CraigslistPostsDataSource",
                        global::LightSwitchApplication.CraigsListPosts.DetailsClass.PropertySetProperties._CraigslistPostsDataSource_Stub,
                        global::LightSwitchApplication.CraigsListPosts.DetailsClass.PropertySetProperties._CraigslistPostsDataSource_Validate,
                        global::LightSwitchApplication.CraigsListPosts.DetailsClass.PropertySetProperties._CraigslistPostsDataSource_CreateQuery,
                        global::LightSwitchApplication.CraigsListPosts.DetailsClass.PropertySetProperties._CraigslistPostsDataSource_SelectionChanged,
                        global::LightSwitchApplication.CraigsListPosts.DetailsClass.PropertySetProperties._CraigslistPostsDataSource_OnCollectionChanged,
                        global::LightSwitchApplication.CraigsListPosts.DetailsClass.PropertySetProperties._CraigslistPostsDataSource_OnLoaded);
                private static void _CraigslistPostsDataSource_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CraigsListPosts.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CraigsListPosts, global::LightSwitchApplication.CraigsListPosts.DetailsClass, global::LightSwitchApplication.CraigslistPost>.Data> c, global::LightSwitchApplication.CraigsListPosts.DetailsClass d, object sf)
                {
                    c(d, ref d._CraigslistPostsDataSource, sf);
                }
                private static void _CraigslistPostsDataSource_Validate(global::LightSwitchApplication.CraigsListPosts s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.CraigslistPostsDataSource_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _CraigslistPostsDataSource_CreateQuery(global::LightSwitchApplication.CraigsListPosts.DetailsClass d, object[] args)
                {
                    return d.CraigslistPostsDataSourceQuery();
                }
                private static void _CraigslistPostsDataSource_SelectionChanged(global::LightSwitchApplication.CraigsListPosts s)
                {
                    s.CraigslistPostsDataSource_SelectionChanged();
                }
                private static void _CraigslistPostsDataSource_OnCollectionChanged(global::LightSwitchApplication.CraigsListPosts s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.CraigslistPostsDataSource_Changed(e);
                }
                private static void _CraigslistPostsDataSource_OnLoaded(global::LightSwitchApplication.CraigsListPosts s, bool succeeded)
                {
                    s.CraigslistPostsDataSource_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.CraigsListPosts, global::LightSwitchApplication.CraigsListPosts.DetailsClass>.Entry
                    CreateNewResponse = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.CraigsListPosts, global::LightSwitchApplication.CraigsListPosts.DetailsClass>.Entry(
                        "CreateNewResponse",
                        global::LightSwitchApplication.CraigsListPosts.DetailsClass.CommandSetProperties._CreateNewResponse_Stub,
                        global::LightSwitchApplication.CraigsListPosts.DetailsClass.CommandSetProperties._CreateNewResponse_CreateExecutableObject);
                private static void _CreateNewResponse_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CraigsListPosts.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.CraigsListPosts, global::LightSwitchApplication.CraigsListPosts.DetailsClass>.Data> c, global::LightSwitchApplication.CraigsListPosts.DetailsClass d, object sf)
                {
                    c(d, ref d._CreateNewResponseCommand, sf);
                }
                private static global::Microsoft.LightSwitch.IExecutable _CreateNewResponse_CreateExecutableObject(global::LightSwitchApplication.CraigsListPosts.DetailsClass d)
                {
                    return ((global::LightSwitchApplication.CraigsListPosts.DetailsClass)d).Methods.CreateNewResponse.CreateInvocation();
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.CraigsListPosts, global::LightSwitchApplication.CraigsListPosts.DetailsClass>.Entry
                    CreateNewResponse = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.CraigsListPosts, global::LightSwitchApplication.CraigsListPosts.DetailsClass>.Entry(
                        "CreateNewResponse",
                        global::LightSwitchApplication.CraigsListPosts.DetailsClass.MethodSetProperties._CreateNewResponse_Stub,
                        global::LightSwitchApplication.CraigsListPosts.DetailsClass.MethodSetProperties._CreateNewResponse_CanInvoke,
                        global::LightSwitchApplication.CraigsListPosts.DetailsClass.MethodSetProperties._CreateNewResponse_InvokeMethod);
                private static void _CreateNewResponse_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CraigsListPosts.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.CraigsListPosts, global::LightSwitchApplication.CraigsListPosts.DetailsClass>.Data> c, global::LightSwitchApplication.CraigsListPosts.DetailsClass d, object sf)
                {
                    c(d, ref d._CreateNewResponseMethod, sf);
                }
                private static global::System.Exception _CreateNewResponse_CanInvoke(global::LightSwitchApplication.CraigsListPosts.DetailsClass d, global::System.Collections.ObjectModel.ReadOnlyCollection<object> args, global::System.Exception ex)
                {
                    bool result = true;
                    d.Screen.CreateNewResponse_CanExecute(ref result);
                    return result ? null : ex;
                }
                private static void _CreateNewResponse_InvokeMethod(global::LightSwitchApplication.CraigsListPosts.DetailsClass d, global::System.Collections.ObjectModel.ReadOnlyCollection<object> args)
                {
                    d.Screen.CreateNewResponse_Execute();
                }

            }
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class CreateNewCraigslistResponse
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.CreateNewCraigslistResponse, global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private CreateNewCraigslistResponse(global::System.Guid CraigslistPostId) : base("LightSwitchApplication:CreateNewCraigslistResponse")
        {
                this.CraigslistPostId = CraigslistPostId;
            global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static CreateNewCraigslistResponse CreateInstance(global::System.Guid CraigslistPostId)
        {
            return new global::LightSwitchApplication.CreateNewCraigslistResponse(
                        CraigslistPostId
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewCraigslistResponse_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewCraigslistResponse_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewCraigslistResponse_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewCraigslistResponse_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewCraigslistResponse_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewCraigslistResponse_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewCraigslistResponse_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void CraigsListResponseProperty_Changed();

        partial void CraigslistPostId_Changed();

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.CraigsListResponse CraigsListResponseProperty
        {
            get 
            {
                return global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass.GetValue(this, global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass.PropertySetProperties.CraigsListResponseProperty);
            }
            set
            {
                global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass.SetValue(this, global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass.PropertySetProperties.CraigsListResponseProperty, value);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CraigsListResponseProperty_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Guid CraigslistPostId
        {
            get 
            {
                return global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass.GetValue(this, global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass.PropertySetProperties.CraigslistPostId);
            }
            set
            {
                global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass.SetValue(this, global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass.PropertySetProperties.CraigslistPostId, value);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CraigslistPostId_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CreateNewCraigslistResponse, global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass, global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass.PropertySet, global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass.CommandSet, global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass.PropertySetProperties.CraigsListResponseProperty;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CreateNewCraigslistResponse, global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass>.Entry
                __CreateNewCraigslistResponseEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CreateNewCraigslistResponse, global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass>.Entry(
                    global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass.__CreateNewCraigslistResponse_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass.__CreateNewCraigslistResponse_InvokeSavingEvent,
                    global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass.__CreateNewCraigslistResponse_InvokeSavedEvent,
                    global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass.__CreateNewCraigslistResponse_InvokeClosingEvent,
                    global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass.__CreateNewCraigslistResponse_InvokeCreated,
                    global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass.__CreateNewCraigslistResponse_InvokeActivated,
                    global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass.__CreateNewCraigslistResponse_InvokeSaveErrorEvent);
            private static void __CreateNewCraigslistResponse_InvokeInitializeDataWorkspace(global::LightSwitchApplication.CreateNewCraigslistResponse s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.CreateNewCraigslistResponse_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __CreateNewCraigslistResponse_InvokeSavingEvent(global::LightSwitchApplication.CreateNewCraigslistResponse s)
            {
                bool handled = false;
                s.CreateNewCraigslistResponse_Saving(ref handled);
                return handled;
            }
            private static void __CreateNewCraigslistResponse_InvokeSavedEvent(global::LightSwitchApplication.CreateNewCraigslistResponse s)
            {
                s.CreateNewCraigslistResponse_Saved();
            }
            private static bool __CreateNewCraigslistResponse_InvokeClosingEvent(global::LightSwitchApplication.CreateNewCraigslistResponse s)
            {
                bool cancel = false;
                s.CreateNewCraigslistResponse_Closing(ref cancel);
                return cancel;
            }
            private static void __CreateNewCraigslistResponse_InvokeCreated(global::LightSwitchApplication.CreateNewCraigslistResponse s)
            {
                s.CreateNewCraigslistResponse_Created();
            }
            private static void __CreateNewCraigslistResponse_InvokeActivated(global::LightSwitchApplication.CreateNewCraigslistResponse s)
            {
                s.CreateNewCraigslistResponse_Activated();
            }
            private static bool __CreateNewCraigslistResponse_InvokeSaveErrorEvent(global::LightSwitchApplication.CreateNewCraigslistResponse s, global::System.Exception ex)
            {
                bool handled = false;
                s.CreateNewCraigslistResponse_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewCraigslistResponse, global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass, global::LightSwitchApplication.CraigsListResponse>.Data _CraigsListResponseProperty;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewCraigslistResponse, global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass, global::System.Guid>.Data _CraigslistPostId;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.CreateNewCraigslistResponse, global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewCraigslistResponse, global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass, global::LightSwitchApplication.CraigsListResponse> CraigsListResponseProperty
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewCraigslistResponse, global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass, global::LightSwitchApplication.CraigsListResponse>)base.GetItem(global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass.PropertySetProperties.CraigsListResponseProperty);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewCraigslistResponse, global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass, global::System.Guid> CraigslistPostId
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewCraigslistResponse, global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass, global::System.Guid>)base.GetItem(global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass.PropertySetProperties.CraigslistPostId);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.CreateNewCraigslistResponse, global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.CreateNewCraigslistResponse, global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewCraigslistResponse, global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass, global::LightSwitchApplication.CraigsListResponse>.Entry
                    CraigsListResponseProperty = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewCraigslistResponse, global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass, global::LightSwitchApplication.CraigsListResponse>.Entry(
                        "CraigsListResponseProperty",
                        false,
                        global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass.PropertySetProperties._CraigsListResponseProperty_Stub,
                        global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass.PropertySetProperties._CraigsListResponseProperty_Validate,
                        global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass.PropertySetProperties._CraigsListResponseProperty_OnValueChanged);
                private static void _CraigsListResponseProperty_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewCraigslistResponse, global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass, global::LightSwitchApplication.CraigsListResponse>.Data> c, global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass d, object sf)
                {
                    c(d, ref d._CraigsListResponseProperty, sf);
                }
                private static void _CraigsListResponseProperty_Validate(global::LightSwitchApplication.CreateNewCraigslistResponse s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.CraigsListResponseProperty_Validate(r);
                }
                private static void _CraigsListResponseProperty_OnValueChanged(global::LightSwitchApplication.CreateNewCraigslistResponse s)
                {
                    s.CraigsListResponseProperty_Changed();
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewCraigslistResponse, global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass, global::System.Guid>.Entry
                    CraigslistPostId = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewCraigslistResponse, global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass, global::System.Guid>.Entry(
                        "CraigslistPostId",
                        false,
                        global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass.PropertySetProperties._CraigslistPostId_Stub,
                        global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass.PropertySetProperties._CraigslistPostId_Validate,
                        global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass.PropertySetProperties._CraigslistPostId_OnValueChanged);
                private static void _CraigslistPostId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewCraigslistResponse, global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass, global::System.Guid>.Data> c, global::LightSwitchApplication.CreateNewCraigslistResponse.DetailsClass d, object sf)
                {
                    c(d, ref d._CraigslistPostId, sf);
                }
                private static void _CraigslistPostId_Validate(global::LightSwitchApplication.CreateNewCraigslistResponse s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.CraigslistPostId_Validate(r);
                }
                private static void _CraigslistPostId_OnValueChanged(global::LightSwitchApplication.CreateNewCraigslistResponse s)
                {
                    s.CraigslistPostId_Changed();
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class Administration
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private Administration() : base("LightSwitchApplication:Administration")
        {
            global::LightSwitchApplication.Administration.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static Administration CreateInstance()
        {
            return new global::LightSwitchApplication.Administration(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Administration_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Administration_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Administration_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Administration_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Administration_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Administration_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Administration_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void CraigslistCities_SelectionChanged();

        partial void CraigslistCities_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CraigslistCities_Loaded(bool succeeded);

        partial void Keywords_SelectionChanged();

        partial void Keywords_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Keywords_Loaded(bool succeeded);

        partial void ServerOperationHistories_SelectionChanged();

        partial void ServerOperationHistories_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ServerOperationHistories_Loaded(bool succeeded);

        /// <summary>
        /// Gets the CraigslistCities visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.CraigslistCity> CraigslistCities
        {
            get
            {
                return global::LightSwitchApplication.Administration.DetailsClass.GetValue(this, global::LightSwitchApplication.Administration.DetailsClass.PropertySetProperties.CraigslistCities);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CraigslistCities_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Gets the Keywords visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Keyword> Keywords
        {
            get
            {
                return global::LightSwitchApplication.Administration.DetailsClass.GetValue(this, global::LightSwitchApplication.Administration.DetailsClass.PropertySetProperties.Keywords);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Keywords_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Gets the ServerOperationHistories visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.ServerOperationHistory> ServerOperationHistories
        {
            get
            {
                return global::LightSwitchApplication.Administration.DetailsClass.GetValue(this, global::LightSwitchApplication.Administration.DetailsClass.PropertySetProperties.ServerOperationHistories);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ServerOperationHistories_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Calls the RunOperation screen method.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void RunOperation()
        {
            this.Details.Methods.RunOperation.CreateInvocation().Execute();
        }
        partial void RunOperation_CanExecute(ref bool result);
        partial void RunOperation_Execute();

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass, global::LightSwitchApplication.Administration.DetailsClass.PropertySet, global::LightSwitchApplication.Administration.DetailsClass.CommandSet, global::LightSwitchApplication.Administration.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.Administration.DetailsClass.PropertySetProperties.CraigslistCities;
                var initializeCommandEntry = global::LightSwitchApplication.Administration.DetailsClass.CommandSetProperties.RunOperation;
                var initializeMethodEntry = global::LightSwitchApplication.Administration.DetailsClass.MethodSetProperties.RunOperation;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass>.Entry
                __AdministrationEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass>.Entry(
                    global::LightSwitchApplication.Administration.DetailsClass.__Administration_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.Administration.DetailsClass.__Administration_InvokeSavingEvent,
                    global::LightSwitchApplication.Administration.DetailsClass.__Administration_InvokeSavedEvent,
                    global::LightSwitchApplication.Administration.DetailsClass.__Administration_InvokeClosingEvent,
                    global::LightSwitchApplication.Administration.DetailsClass.__Administration_InvokeCreated,
                    global::LightSwitchApplication.Administration.DetailsClass.__Administration_InvokeActivated,
                    global::LightSwitchApplication.Administration.DetailsClass.__Administration_InvokeSaveErrorEvent);
            private static void __Administration_InvokeInitializeDataWorkspace(global::LightSwitchApplication.Administration s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.Administration_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __Administration_InvokeSavingEvent(global::LightSwitchApplication.Administration s)
            {
                bool handled = false;
                s.Administration_Saving(ref handled);
                return handled;
            }
            private static void __Administration_InvokeSavedEvent(global::LightSwitchApplication.Administration s)
            {
                s.Administration_Saved();
            }
            private static bool __Administration_InvokeClosingEvent(global::LightSwitchApplication.Administration s)
            {
                bool cancel = false;
                s.Administration_Closing(ref cancel);
                return cancel;
            }
            private static void __Administration_InvokeCreated(global::LightSwitchApplication.Administration s)
            {
                s.Administration_Created();
            }
            private static void __Administration_InvokeActivated(global::LightSwitchApplication.Administration s)
            {
                s.Administration_Activated();
            }
            private static bool __Administration_InvokeSaveErrorEvent(global::LightSwitchApplication.Administration s, global::System.Exception ex)
            {
                bool handled = false;
                s.Administration_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.Administration.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.Administration.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.Administration.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable CraigslistCitiesQuery()
            {
                return this.Screen.DataWorkspace.MarketingData.CraigslistCities;
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable KeywordsQuery()
            {
                return this.Screen.DataWorkspace.MarketingData.Keywords;
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable ServerOperationHistoriesQuery()
            {
                return global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                    this.Screen.DataWorkspace.MarketingData.ServerOperationHistories,
                    "ServerOperation");
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass, global::LightSwitchApplication.CraigslistCity>.Data _CraigslistCities;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass, global::LightSwitchApplication.Keyword>.Data _Keywords;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass, global::LightSwitchApplication.ServerOperationHistory>.Data _ServerOperationHistories;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass>.Data _RunOperationCommand;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass>.Data _RunOperationMethod;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass, global::LightSwitchApplication.CraigslistCity> CraigslistCities
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass, global::LightSwitchApplication.CraigslistCity>)base.GetItem(global::LightSwitchApplication.Administration.DetailsClass.PropertySetProperties.CraigslistCities);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass, global::LightSwitchApplication.Keyword> Keywords
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass, global::LightSwitchApplication.Keyword>)base.GetItem(global::LightSwitchApplication.Administration.DetailsClass.PropertySetProperties.Keywords);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass, global::LightSwitchApplication.ServerOperationHistory> ServerOperationHistories
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass, global::LightSwitchApplication.ServerOperationHistory>)base.GetItem(global::LightSwitchApplication.Administration.DetailsClass.PropertySetProperties.ServerOperationHistories);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass> RunOperation
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass>)base.GetItem(global::LightSwitchApplication.Administration.DetailsClass.CommandSetProperties.RunOperation);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass> RunOperation
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass>)base.GetItem(global::LightSwitchApplication.Administration.DetailsClass.MethodSetProperties.RunOperation);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass, global::LightSwitchApplication.CraigslistCity>.Entry
                    CraigslistCities = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass, global::LightSwitchApplication.CraigslistCity>.Entry(
                        "CraigslistCities",
                        global::LightSwitchApplication.Administration.DetailsClass.PropertySetProperties._CraigslistCities_Stub,
                        global::LightSwitchApplication.Administration.DetailsClass.PropertySetProperties._CraigslistCities_Validate,
                        global::LightSwitchApplication.Administration.DetailsClass.PropertySetProperties._CraigslistCities_CreateQuery,
                        global::LightSwitchApplication.Administration.DetailsClass.PropertySetProperties._CraigslistCities_SelectionChanged,
                        global::LightSwitchApplication.Administration.DetailsClass.PropertySetProperties._CraigslistCities_OnCollectionChanged,
                        global::LightSwitchApplication.Administration.DetailsClass.PropertySetProperties._CraigslistCities_OnLoaded);
                private static void _CraigslistCities_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Administration.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass, global::LightSwitchApplication.CraigslistCity>.Data> c, global::LightSwitchApplication.Administration.DetailsClass d, object sf)
                {
                    c(d, ref d._CraigslistCities, sf);
                }
                private static void _CraigslistCities_Validate(global::LightSwitchApplication.Administration s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.CraigslistCities_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _CraigslistCities_CreateQuery(global::LightSwitchApplication.Administration.DetailsClass d, object[] args)
                {
                    return d.CraigslistCitiesQuery();
                }
                private static void _CraigslistCities_SelectionChanged(global::LightSwitchApplication.Administration s)
                {
                    s.CraigslistCities_SelectionChanged();
                }
                private static void _CraigslistCities_OnCollectionChanged(global::LightSwitchApplication.Administration s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.CraigslistCities_Changed(e);
                }
                private static void _CraigslistCities_OnLoaded(global::LightSwitchApplication.Administration s, bool succeeded)
                {
                    s.CraigslistCities_Loaded(succeeded);
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass, global::LightSwitchApplication.Keyword>.Entry
                    Keywords = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass, global::LightSwitchApplication.Keyword>.Entry(
                        "Keywords",
                        global::LightSwitchApplication.Administration.DetailsClass.PropertySetProperties._Keywords_Stub,
                        global::LightSwitchApplication.Administration.DetailsClass.PropertySetProperties._Keywords_Validate,
                        global::LightSwitchApplication.Administration.DetailsClass.PropertySetProperties._Keywords_CreateQuery,
                        global::LightSwitchApplication.Administration.DetailsClass.PropertySetProperties._Keywords_SelectionChanged,
                        global::LightSwitchApplication.Administration.DetailsClass.PropertySetProperties._Keywords_OnCollectionChanged,
                        global::LightSwitchApplication.Administration.DetailsClass.PropertySetProperties._Keywords_OnLoaded);
                private static void _Keywords_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Administration.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass, global::LightSwitchApplication.Keyword>.Data> c, global::LightSwitchApplication.Administration.DetailsClass d, object sf)
                {
                    c(d, ref d._Keywords, sf);
                }
                private static void _Keywords_Validate(global::LightSwitchApplication.Administration s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Keywords_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Keywords_CreateQuery(global::LightSwitchApplication.Administration.DetailsClass d, object[] args)
                {
                    return d.KeywordsQuery();
                }
                private static void _Keywords_SelectionChanged(global::LightSwitchApplication.Administration s)
                {
                    s.Keywords_SelectionChanged();
                }
                private static void _Keywords_OnCollectionChanged(global::LightSwitchApplication.Administration s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.Keywords_Changed(e);
                }
                private static void _Keywords_OnLoaded(global::LightSwitchApplication.Administration s, bool succeeded)
                {
                    s.Keywords_Loaded(succeeded);
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass, global::LightSwitchApplication.ServerOperationHistory>.Entry
                    ServerOperationHistories = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass, global::LightSwitchApplication.ServerOperationHistory>.Entry(
                        "ServerOperationHistories",
                        global::LightSwitchApplication.Administration.DetailsClass.PropertySetProperties._ServerOperationHistories_Stub,
                        global::LightSwitchApplication.Administration.DetailsClass.PropertySetProperties._ServerOperationHistories_Validate,
                        global::LightSwitchApplication.Administration.DetailsClass.PropertySetProperties._ServerOperationHistories_CreateQuery,
                        global::LightSwitchApplication.Administration.DetailsClass.PropertySetProperties._ServerOperationHistories_SelectionChanged,
                        global::LightSwitchApplication.Administration.DetailsClass.PropertySetProperties._ServerOperationHistories_OnCollectionChanged,
                        global::LightSwitchApplication.Administration.DetailsClass.PropertySetProperties._ServerOperationHistories_OnLoaded);
                private static void _ServerOperationHistories_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Administration.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass, global::LightSwitchApplication.ServerOperationHistory>.Data> c, global::LightSwitchApplication.Administration.DetailsClass d, object sf)
                {
                    c(d, ref d._ServerOperationHistories, sf);
                }
                private static void _ServerOperationHistories_Validate(global::LightSwitchApplication.Administration s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.ServerOperationHistories_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _ServerOperationHistories_CreateQuery(global::LightSwitchApplication.Administration.DetailsClass d, object[] args)
                {
                    return d.ServerOperationHistoriesQuery();
                }
                private static void _ServerOperationHistories_SelectionChanged(global::LightSwitchApplication.Administration s)
                {
                    s.ServerOperationHistories_SelectionChanged();
                }
                private static void _ServerOperationHistories_OnCollectionChanged(global::LightSwitchApplication.Administration s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.ServerOperationHistories_Changed(e);
                }
                private static void _ServerOperationHistories_OnLoaded(global::LightSwitchApplication.Administration s, bool succeeded)
                {
                    s.ServerOperationHistories_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass>.Entry
                    RunOperation = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass>.Entry(
                        "RunOperation",
                        global::LightSwitchApplication.Administration.DetailsClass.CommandSetProperties._RunOperation_Stub,
                        global::LightSwitchApplication.Administration.DetailsClass.CommandSetProperties._RunOperation_CreateExecutableObject);
                private static void _RunOperation_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Administration.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass>.Data> c, global::LightSwitchApplication.Administration.DetailsClass d, object sf)
                {
                    c(d, ref d._RunOperationCommand, sf);
                }
                private static global::Microsoft.LightSwitch.IExecutable _RunOperation_CreateExecutableObject(global::LightSwitchApplication.Administration.DetailsClass d)
                {
                    return ((global::LightSwitchApplication.Administration.DetailsClass)d).Methods.RunOperation.CreateInvocation();
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass>.Entry
                    RunOperation = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass>.Entry(
                        "RunOperation",
                        global::LightSwitchApplication.Administration.DetailsClass.MethodSetProperties._RunOperation_Stub,
                        global::LightSwitchApplication.Administration.DetailsClass.MethodSetProperties._RunOperation_CanInvoke,
                        global::LightSwitchApplication.Administration.DetailsClass.MethodSetProperties._RunOperation_InvokeMethod);
                private static void _RunOperation_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Administration.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.Administration, global::LightSwitchApplication.Administration.DetailsClass>.Data> c, global::LightSwitchApplication.Administration.DetailsClass d, object sf)
                {
                    c(d, ref d._RunOperationMethod, sf);
                }
                private static global::System.Exception _RunOperation_CanInvoke(global::LightSwitchApplication.Administration.DetailsClass d, global::System.Collections.ObjectModel.ReadOnlyCollection<object> args, global::System.Exception ex)
                {
                    bool result = true;
                    d.Screen.RunOperation_CanExecute(ref result);
                    return result ? null : ex;
                }
                private static void _RunOperation_InvokeMethod(global::LightSwitchApplication.Administration.DetailsClass d, global::System.Collections.ObjectModel.ReadOnlyCollection<object> args)
                {
                    d.Screen.RunOperation_Execute();
                }

            }
        }
    }
}
