

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class c_Error : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the c_Error entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public c_Error()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public c_Error(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.c_Error> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.c_Error.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_Error_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_Error_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return global::LightSwitchApplication.c_Error.DetailsClass.GetValue(this, global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.c_Error.DetailsClass.SetValue(this, global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string OriginatingClassName
        {
            get
            {
                return global::LightSwitchApplication.c_Error.DetailsClass.GetValue(this, global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties.OriginatingClassName);
            }
            set
            {
                global::LightSwitchApplication.c_Error.DetailsClass.SetValue(this, global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties.OriginatingClassName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OriginatingClassName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OriginatingClassName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OriginatingClassName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string MethodName
        {
            get
            {
                return global::LightSwitchApplication.c_Error.DetailsClass.GetValue(this, global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties.MethodName);
            }
            set
            {
                global::LightSwitchApplication.c_Error.DetailsClass.SetValue(this, global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties.MethodName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MethodName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MethodName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MethodName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ExceptionTypeName
        {
            get
            {
                return global::LightSwitchApplication.c_Error.DetailsClass.GetValue(this, global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties.ExceptionTypeName);
            }
            set
            {
                global::LightSwitchApplication.c_Error.DetailsClass.SetValue(this, global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties.ExceptionTypeName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ExceptionTypeName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ExceptionTypeName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ExceptionTypeName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ExceptionMessage
        {
            get
            {
                return global::LightSwitchApplication.c_Error.DetailsClass.GetValue(this, global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties.ExceptionMessage);
            }
            set
            {
                global::LightSwitchApplication.c_Error.DetailsClass.SetValue(this, global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties.ExceptionMessage, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ExceptionMessage_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ExceptionMessage_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ExceptionMessage_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ErrorMessage
        {
            get
            {
                return global::LightSwitchApplication.c_Error.DetailsClass.GetValue(this, global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties.ErrorMessage);
            }
            set
            {
                global::LightSwitchApplication.c_Error.DetailsClass.SetValue(this, global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties.ErrorMessage, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ErrorMessage_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ErrorMessage_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ErrorMessage_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ErrorData
        {
            get
            {
                return global::LightSwitchApplication.c_Error.DetailsClass.GetValue(this, global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties.ErrorData);
            }
            set
            {
                global::LightSwitchApplication.c_Error.DetailsClass.SetValue(this, global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties.ErrorData, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ErrorData_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ErrorData_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ErrorData_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.c_Error,
                global::LightSwitchApplication.c_Error.DetailsClass,
                global::LightSwitchApplication.c_Error.DetailsClass.IImplementation,
                global::LightSwitchApplication.c_Error.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass>.Entry
                __c_ErrorEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass>.Entry(
                    global::LightSwitchApplication.c_Error.DetailsClass.__c_Error_CreateNew,
                    global::LightSwitchApplication.c_Error.DetailsClass.__c_Error_Created,
                    global::LightSwitchApplication.c_Error.DetailsClass.__c_Error_AllowSaveWithErrors);
            private static global::LightSwitchApplication.c_Error __c_Error_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.c_Error> es)
            {
                return new global::LightSwitchApplication.c_Error(es);
            }
            private static void __c_Error_Created(global::LightSwitchApplication.c_Error e)
            {
                e.c_Error_Created();
            }
            private static bool __c_Error_AllowSaveWithErrors(global::LightSwitchApplication.c_Error e)
            {
                bool result = false;
                e.c_Error_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.c_Error.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, global::System.Guid> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, global::System.Guid>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, string> OriginatingClassName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties.OriginatingClassName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, string> MethodName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties.MethodName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, string> ExceptionTypeName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties.ExceptionTypeName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, string> ExceptionMessage
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties.ExceptionMessage) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, string> ErrorMessage
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties.ErrorMessage) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, string> ErrorData
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties.ErrorData) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, string>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new global::System.Guid Id { get; set; }
                new string OriginatingClassName { get; set; }
                new string MethodName { get; set; }
                new string ExceptionTypeName { get; set; }
                new string ExceptionMessage { get; set; }
                new string ErrorMessage { get; set; }
                new string ErrorData { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, global::System.Guid>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, global::System.Guid>.Entry(
                        "Id",
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.c_Error.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, global::System.Guid>.Data> c, global::LightSwitchApplication.c_Error.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.c_Error e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.c_Error e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static global::System.Guid _Id_GetImplementationValue(global::LightSwitchApplication.c_Error.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.c_Error.DetailsClass d, global::System.Guid v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.c_Error e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, string>.Entry
                    OriginatingClassName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, string>.Entry(
                        "OriginatingClassName",
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._OriginatingClassName_Stub,
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._OriginatingClassName_ComputeIsReadOnly,
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._OriginatingClassName_Validate,
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._OriginatingClassName_GetImplementationValue,
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._OriginatingClassName_SetImplementationValue,
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._OriginatingClassName_OnValueChanged);
                private static void _OriginatingClassName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.c_Error.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, string>.Data> c, global::LightSwitchApplication.c_Error.DetailsClass d, object sf)
                {
                    c(d, ref d._OriginatingClassName, sf);
                }
                private static bool _OriginatingClassName_ComputeIsReadOnly(global::LightSwitchApplication.c_Error e)
                {
                    bool result = false;
                    e.OriginatingClassName_IsReadOnly(ref result);
                    return result;
                }
                private static void _OriginatingClassName_Validate(global::LightSwitchApplication.c_Error e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.OriginatingClassName_Validate(r);
                }
                private static string _OriginatingClassName_GetImplementationValue(global::LightSwitchApplication.c_Error.DetailsClass d)
                {
                    return d.ImplementationEntity.OriginatingClassName;
                }
                private static void _OriginatingClassName_SetImplementationValue(global::LightSwitchApplication.c_Error.DetailsClass d, string v)
                {
                    d.ImplementationEntity.OriginatingClassName = v;
                }
                private static void _OriginatingClassName_OnValueChanged(global::LightSwitchApplication.c_Error e)
                {
                    e.OriginatingClassName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, string>.Entry
                    MethodName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, string>.Entry(
                        "MethodName",
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._MethodName_Stub,
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._MethodName_ComputeIsReadOnly,
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._MethodName_Validate,
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._MethodName_GetImplementationValue,
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._MethodName_SetImplementationValue,
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._MethodName_OnValueChanged);
                private static void _MethodName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.c_Error.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, string>.Data> c, global::LightSwitchApplication.c_Error.DetailsClass d, object sf)
                {
                    c(d, ref d._MethodName, sf);
                }
                private static bool _MethodName_ComputeIsReadOnly(global::LightSwitchApplication.c_Error e)
                {
                    bool result = false;
                    e.MethodName_IsReadOnly(ref result);
                    return result;
                }
                private static void _MethodName_Validate(global::LightSwitchApplication.c_Error e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.MethodName_Validate(r);
                }
                private static string _MethodName_GetImplementationValue(global::LightSwitchApplication.c_Error.DetailsClass d)
                {
                    return d.ImplementationEntity.MethodName;
                }
                private static void _MethodName_SetImplementationValue(global::LightSwitchApplication.c_Error.DetailsClass d, string v)
                {
                    d.ImplementationEntity.MethodName = v;
                }
                private static void _MethodName_OnValueChanged(global::LightSwitchApplication.c_Error e)
                {
                    e.MethodName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, string>.Entry
                    ExceptionTypeName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, string>.Entry(
                        "ExceptionTypeName",
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._ExceptionTypeName_Stub,
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._ExceptionTypeName_ComputeIsReadOnly,
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._ExceptionTypeName_Validate,
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._ExceptionTypeName_GetImplementationValue,
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._ExceptionTypeName_SetImplementationValue,
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._ExceptionTypeName_OnValueChanged);
                private static void _ExceptionTypeName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.c_Error.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, string>.Data> c, global::LightSwitchApplication.c_Error.DetailsClass d, object sf)
                {
                    c(d, ref d._ExceptionTypeName, sf);
                }
                private static bool _ExceptionTypeName_ComputeIsReadOnly(global::LightSwitchApplication.c_Error e)
                {
                    bool result = false;
                    e.ExceptionTypeName_IsReadOnly(ref result);
                    return result;
                }
                private static void _ExceptionTypeName_Validate(global::LightSwitchApplication.c_Error e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ExceptionTypeName_Validate(r);
                }
                private static string _ExceptionTypeName_GetImplementationValue(global::LightSwitchApplication.c_Error.DetailsClass d)
                {
                    return d.ImplementationEntity.ExceptionTypeName;
                }
                private static void _ExceptionTypeName_SetImplementationValue(global::LightSwitchApplication.c_Error.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ExceptionTypeName = v;
                }
                private static void _ExceptionTypeName_OnValueChanged(global::LightSwitchApplication.c_Error e)
                {
                    e.ExceptionTypeName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, string>.Entry
                    ExceptionMessage = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, string>.Entry(
                        "ExceptionMessage",
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._ExceptionMessage_Stub,
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._ExceptionMessage_ComputeIsReadOnly,
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._ExceptionMessage_Validate,
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._ExceptionMessage_GetImplementationValue,
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._ExceptionMessage_SetImplementationValue,
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._ExceptionMessage_OnValueChanged);
                private static void _ExceptionMessage_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.c_Error.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, string>.Data> c, global::LightSwitchApplication.c_Error.DetailsClass d, object sf)
                {
                    c(d, ref d._ExceptionMessage, sf);
                }
                private static bool _ExceptionMessage_ComputeIsReadOnly(global::LightSwitchApplication.c_Error e)
                {
                    bool result = false;
                    e.ExceptionMessage_IsReadOnly(ref result);
                    return result;
                }
                private static void _ExceptionMessage_Validate(global::LightSwitchApplication.c_Error e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ExceptionMessage_Validate(r);
                }
                private static string _ExceptionMessage_GetImplementationValue(global::LightSwitchApplication.c_Error.DetailsClass d)
                {
                    return d.ImplementationEntity.ExceptionMessage;
                }
                private static void _ExceptionMessage_SetImplementationValue(global::LightSwitchApplication.c_Error.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ExceptionMessage = v;
                }
                private static void _ExceptionMessage_OnValueChanged(global::LightSwitchApplication.c_Error e)
                {
                    e.ExceptionMessage_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, string>.Entry
                    ErrorMessage = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, string>.Entry(
                        "ErrorMessage",
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._ErrorMessage_Stub,
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._ErrorMessage_ComputeIsReadOnly,
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._ErrorMessage_Validate,
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._ErrorMessage_GetImplementationValue,
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._ErrorMessage_SetImplementationValue,
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._ErrorMessage_OnValueChanged);
                private static void _ErrorMessage_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.c_Error.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, string>.Data> c, global::LightSwitchApplication.c_Error.DetailsClass d, object sf)
                {
                    c(d, ref d._ErrorMessage, sf);
                }
                private static bool _ErrorMessage_ComputeIsReadOnly(global::LightSwitchApplication.c_Error e)
                {
                    bool result = false;
                    e.ErrorMessage_IsReadOnly(ref result);
                    return result;
                }
                private static void _ErrorMessage_Validate(global::LightSwitchApplication.c_Error e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ErrorMessage_Validate(r);
                }
                private static string _ErrorMessage_GetImplementationValue(global::LightSwitchApplication.c_Error.DetailsClass d)
                {
                    return d.ImplementationEntity.ErrorMessage;
                }
                private static void _ErrorMessage_SetImplementationValue(global::LightSwitchApplication.c_Error.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ErrorMessage = v;
                }
                private static void _ErrorMessage_OnValueChanged(global::LightSwitchApplication.c_Error e)
                {
                    e.ErrorMessage_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, string>.Entry
                    ErrorData = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, string>.Entry(
                        "ErrorData",
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._ErrorData_Stub,
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._ErrorData_ComputeIsReadOnly,
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._ErrorData_Validate,
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._ErrorData_GetImplementationValue,
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._ErrorData_SetImplementationValue,
                        global::LightSwitchApplication.c_Error.DetailsClass.PropertySetProperties._ErrorData_OnValueChanged);
                private static void _ErrorData_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.c_Error.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, string>.Data> c, global::LightSwitchApplication.c_Error.DetailsClass d, object sf)
                {
                    c(d, ref d._ErrorData, sf);
                }
                private static bool _ErrorData_ComputeIsReadOnly(global::LightSwitchApplication.c_Error e)
                {
                    bool result = false;
                    e.ErrorData_IsReadOnly(ref result);
                    return result;
                }
                private static void _ErrorData_Validate(global::LightSwitchApplication.c_Error e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ErrorData_Validate(r);
                }
                private static string _ErrorData_GetImplementationValue(global::LightSwitchApplication.c_Error.DetailsClass d)
                {
                    return d.ImplementationEntity.ErrorData;
                }
                private static void _ErrorData_SetImplementationValue(global::LightSwitchApplication.c_Error.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ErrorData = v;
                }
                private static void _ErrorData_OnValueChanged(global::LightSwitchApplication.c_Error e)
                {
                    e.ErrorData_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, global::System.Guid>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, string>.Data _OriginatingClassName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, string>.Data _MethodName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, string>.Data _ExceptionTypeName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, string>.Data _ExceptionMessage;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, string>.Data _ErrorMessage;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Error, global::LightSwitchApplication.c_Error.DetailsClass, string>.Data _ErrorData;
            
        }
    
        #endregion
    }
    
    #endregion
}
