

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class UserPostListFilterItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the UserPostListFilterItem entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public UserPostListFilterItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public UserPostListFilterItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.UserPostListFilterItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserPostListFilterItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserPostListFilterItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.GetValue(this, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.SetValue(this, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Guid UserId
        {
            get
            {
                return global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.GetValue(this, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.UserId);
            }
            set
            {
                global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.SetValue(this, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.UserId, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> PostStartDate
        {
            get
            {
                return global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.GetValue(this, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.PostStartDate);
            }
            set
            {
                global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.SetValue(this, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.PostStartDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PostStartDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PostStartDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PostStartDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> PostEndDate
        {
            get
            {
                return global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.GetValue(this, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.PostEndDate);
            }
            set
            {
                global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.SetValue(this, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.PostEndDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PostEndDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PostEndDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PostEndDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> ResponseStartDate
        {
            get
            {
                return global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.GetValue(this, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.ResponseStartDate);
            }
            set
            {
                global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.SetValue(this, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.ResponseStartDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ResponseStartDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ResponseStartDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ResponseStartDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> ResponseEndDate
        {
            get
            {
                return global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.GetValue(this, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.ResponseEndDate);
            }
            set
            {
                global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.SetValue(this, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.ResponseEndDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ResponseEndDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ResponseEndDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ResponseEndDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string FilteredKeywords
        {
            get
            {
                return global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.GetValue(this, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.FilteredKeywords);
            }
            set
            {
                global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.SetValue(this, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.FilteredKeywords, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FilteredKeywords_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FilteredKeywords_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FilteredKeywords_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string FilteredCities
        {
            get
            {
                return global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.GetValue(this, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.FilteredCities);
            }
            set
            {
                global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.SetValue(this, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.FilteredCities, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FilteredCities_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FilteredCities_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FilteredCities_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string FilteredStates
        {
            get
            {
                return global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.GetValue(this, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.FilteredStates);
            }
            set
            {
                global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.SetValue(this, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.FilteredStates, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FilteredStates_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FilteredStates_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FilteredStates_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string FilteredCountries
        {
            get
            {
                return global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.GetValue(this, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.FilteredCountries);
            }
            set
            {
                global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.SetValue(this, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.FilteredCountries, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FilteredCountries_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FilteredCountries_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FilteredCountries_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool ShowResponded
        {
            get
            {
                return global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.GetValue(this, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.ShowResponded);
            }
            set
            {
                global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.SetValue(this, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.ShowResponded, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ShowResponded_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ShowResponded_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ShowResponded_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool ShowNotResponded
        {
            get
            {
                return global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.GetValue(this, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.ShowNotResponded);
            }
            set
            {
                global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.SetValue(this, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.ShowNotResponded, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ShowNotResponded_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ShowNotResponded_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ShowNotResponded_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool FiltersEnabled
        {
            get
            {
                return global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.GetValue(this, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.FiltersEnabled);
            }
            set
            {
                global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.SetValue(this, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.FiltersEnabled, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FiltersEnabled_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FiltersEnabled_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FiltersEnabled_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.UserPostListFilterItem,
                global::LightSwitchApplication.UserPostListFilterItem.DetailsClass,
                global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass>.Entry
                __UserPostListFilterItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.__UserPostListFilterItem_CreateNew,
                    global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.__UserPostListFilterItem_Created,
                    global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.__UserPostListFilterItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.UserPostListFilterItem __UserPostListFilterItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.UserPostListFilterItem> es)
            {
                return new global::LightSwitchApplication.UserPostListFilterItem(es);
            }
            private static void __UserPostListFilterItem_Created(global::LightSwitchApplication.UserPostListFilterItem e)
            {
                e.UserPostListFilterItem_Created();
            }
            private static bool __UserPostListFilterItem_AllowSaveWithErrors(global::LightSwitchApplication.UserPostListFilterItem e)
            {
                bool result = false;
                e.UserPostListFilterItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::System.Guid> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::System.Guid>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::System.Guid> UserId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.UserId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::System.Guid>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::System.Nullable<global::System.DateTime>> PostStartDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.PostStartDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::System.Nullable<global::System.DateTime>> PostEndDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.PostEndDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::System.Nullable<global::System.DateTime>> ResponseStartDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.ResponseStartDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::System.Nullable<global::System.DateTime>> ResponseEndDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.ResponseEndDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, string> FilteredKeywords
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.FilteredKeywords) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, string> FilteredCities
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.FilteredCities) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, string> FilteredStates
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.FilteredStates) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, string> FilteredCountries
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.FilteredCountries) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, bool> ShowResponded
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.ShowResponded) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, bool>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, bool> ShowNotResponded
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.ShowNotResponded) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, bool>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, bool> FiltersEnabled
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties.FiltersEnabled) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, bool>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new global::System.Guid Id { get; set; }
                new global::System.Guid UserId { get; set; }
                new global::System.Nullable<global::System.DateTime> PostStartDate { get; set; }
                new global::System.Nullable<global::System.DateTime> PostEndDate { get; set; }
                new global::System.Nullable<global::System.DateTime> ResponseStartDate { get; set; }
                new global::System.Nullable<global::System.DateTime> ResponseEndDate { get; set; }
                new string FilteredKeywords { get; set; }
                new string FilteredCities { get; set; }
                new string FilteredStates { get; set; }
                new string FilteredCountries { get; set; }
                new bool ShowResponded { get; set; }
                new bool ShowNotResponded { get; set; }
                new bool FiltersEnabled { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::System.Guid>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::System.Guid>.Entry(
                        "Id",
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::System.Guid>.Data> c, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.UserPostListFilterItem e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.UserPostListFilterItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static global::System.Guid _Id_GetImplementationValue(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d, global::System.Guid v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.UserPostListFilterItem e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::System.Guid>.Entry
                    UserId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::System.Guid>.Entry(
                        "UserId",
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._UserId_Stub,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._UserId_ComputeIsReadOnly,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._UserId_Validate,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._UserId_GetImplementationValue,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._UserId_SetImplementationValue,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._UserId_OnValueChanged);
                private static void _UserId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::System.Guid>.Data> c, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d, object sf)
                {
                    c(d, ref d._UserId, sf);
                }
                private static bool _UserId_ComputeIsReadOnly(global::LightSwitchApplication.UserPostListFilterItem e)
                {
                    bool result = false;
                    e.UserId_IsReadOnly(ref result);
                    return result;
                }
                private static void _UserId_Validate(global::LightSwitchApplication.UserPostListFilterItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.UserId_Validate(r);
                }
                private static global::System.Guid _UserId_GetImplementationValue(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d)
                {
                    return d.ImplementationEntity.UserId;
                }
                private static void _UserId_SetImplementationValue(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d, global::System.Guid v)
                {
                    d.ImplementationEntity.UserId = v;
                }
                private static void _UserId_OnValueChanged(global::LightSwitchApplication.UserPostListFilterItem e)
                {
                    e.UserId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    PostStartDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "PostStartDate",
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._PostStartDate_Stub,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._PostStartDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._PostStartDate_Validate,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._PostStartDate_GetImplementationValue,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._PostStartDate_SetImplementationValue,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._PostStartDate_OnValueChanged);
                private static void _PostStartDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d, object sf)
                {
                    c(d, ref d._PostStartDate, sf);
                }
                private static bool _PostStartDate_ComputeIsReadOnly(global::LightSwitchApplication.UserPostListFilterItem e)
                {
                    bool result = false;
                    e.PostStartDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _PostStartDate_Validate(global::LightSwitchApplication.UserPostListFilterItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PostStartDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _PostStartDate_GetImplementationValue(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d)
                {
                    return d.ImplementationEntity.PostStartDate;
                }
                private static void _PostStartDate_SetImplementationValue(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.PostStartDate = global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _PostStartDate_OnValueChanged(global::LightSwitchApplication.UserPostListFilterItem e)
                {
                    e.PostStartDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    PostEndDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "PostEndDate",
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._PostEndDate_Stub,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._PostEndDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._PostEndDate_Validate,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._PostEndDate_GetImplementationValue,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._PostEndDate_SetImplementationValue,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._PostEndDate_OnValueChanged);
                private static void _PostEndDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d, object sf)
                {
                    c(d, ref d._PostEndDate, sf);
                }
                private static bool _PostEndDate_ComputeIsReadOnly(global::LightSwitchApplication.UserPostListFilterItem e)
                {
                    bool result = false;
                    e.PostEndDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _PostEndDate_Validate(global::LightSwitchApplication.UserPostListFilterItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PostEndDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _PostEndDate_GetImplementationValue(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d)
                {
                    return d.ImplementationEntity.PostEndDate;
                }
                private static void _PostEndDate_SetImplementationValue(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.PostEndDate = global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _PostEndDate_OnValueChanged(global::LightSwitchApplication.UserPostListFilterItem e)
                {
                    e.PostEndDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    ResponseStartDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "ResponseStartDate",
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._ResponseStartDate_Stub,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._ResponseStartDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._ResponseStartDate_Validate,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._ResponseStartDate_GetImplementationValue,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._ResponseStartDate_SetImplementationValue,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._ResponseStartDate_OnValueChanged);
                private static void _ResponseStartDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d, object sf)
                {
                    c(d, ref d._ResponseStartDate, sf);
                }
                private static bool _ResponseStartDate_ComputeIsReadOnly(global::LightSwitchApplication.UserPostListFilterItem e)
                {
                    bool result = false;
                    e.ResponseStartDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _ResponseStartDate_Validate(global::LightSwitchApplication.UserPostListFilterItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ResponseStartDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _ResponseStartDate_GetImplementationValue(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d)
                {
                    return d.ImplementationEntity.ResponseStartDate;
                }
                private static void _ResponseStartDate_SetImplementationValue(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.ResponseStartDate = global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _ResponseStartDate_OnValueChanged(global::LightSwitchApplication.UserPostListFilterItem e)
                {
                    e.ResponseStartDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    ResponseEndDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "ResponseEndDate",
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._ResponseEndDate_Stub,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._ResponseEndDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._ResponseEndDate_Validate,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._ResponseEndDate_GetImplementationValue,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._ResponseEndDate_SetImplementationValue,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._ResponseEndDate_OnValueChanged);
                private static void _ResponseEndDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d, object sf)
                {
                    c(d, ref d._ResponseEndDate, sf);
                }
                private static bool _ResponseEndDate_ComputeIsReadOnly(global::LightSwitchApplication.UserPostListFilterItem e)
                {
                    bool result = false;
                    e.ResponseEndDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _ResponseEndDate_Validate(global::LightSwitchApplication.UserPostListFilterItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ResponseEndDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _ResponseEndDate_GetImplementationValue(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d)
                {
                    return d.ImplementationEntity.ResponseEndDate;
                }
                private static void _ResponseEndDate_SetImplementationValue(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.ResponseEndDate = global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _ResponseEndDate_OnValueChanged(global::LightSwitchApplication.UserPostListFilterItem e)
                {
                    e.ResponseEndDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, string>.Entry
                    FilteredKeywords = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, string>.Entry(
                        "FilteredKeywords",
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._FilteredKeywords_Stub,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._FilteredKeywords_ComputeIsReadOnly,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._FilteredKeywords_Validate,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._FilteredKeywords_GetImplementationValue,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._FilteredKeywords_SetImplementationValue,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._FilteredKeywords_OnValueChanged);
                private static void _FilteredKeywords_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d, object sf)
                {
                    c(d, ref d._FilteredKeywords, sf);
                }
                private static bool _FilteredKeywords_ComputeIsReadOnly(global::LightSwitchApplication.UserPostListFilterItem e)
                {
                    bool result = false;
                    e.FilteredKeywords_IsReadOnly(ref result);
                    return result;
                }
                private static void _FilteredKeywords_Validate(global::LightSwitchApplication.UserPostListFilterItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.FilteredKeywords_Validate(r);
                }
                private static string _FilteredKeywords_GetImplementationValue(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d)
                {
                    return d.ImplementationEntity.FilteredKeywords;
                }
                private static void _FilteredKeywords_SetImplementationValue(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.FilteredKeywords = v;
                }
                private static void _FilteredKeywords_OnValueChanged(global::LightSwitchApplication.UserPostListFilterItem e)
                {
                    e.FilteredKeywords_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, string>.Entry
                    FilteredCities = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, string>.Entry(
                        "FilteredCities",
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._FilteredCities_Stub,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._FilteredCities_ComputeIsReadOnly,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._FilteredCities_Validate,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._FilteredCities_GetImplementationValue,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._FilteredCities_SetImplementationValue,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._FilteredCities_OnValueChanged);
                private static void _FilteredCities_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d, object sf)
                {
                    c(d, ref d._FilteredCities, sf);
                }
                private static bool _FilteredCities_ComputeIsReadOnly(global::LightSwitchApplication.UserPostListFilterItem e)
                {
                    bool result = false;
                    e.FilteredCities_IsReadOnly(ref result);
                    return result;
                }
                private static void _FilteredCities_Validate(global::LightSwitchApplication.UserPostListFilterItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.FilteredCities_Validate(r);
                }
                private static string _FilteredCities_GetImplementationValue(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d)
                {
                    return d.ImplementationEntity.FilteredCities;
                }
                private static void _FilteredCities_SetImplementationValue(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.FilteredCities = v;
                }
                private static void _FilteredCities_OnValueChanged(global::LightSwitchApplication.UserPostListFilterItem e)
                {
                    e.FilteredCities_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, string>.Entry
                    FilteredStates = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, string>.Entry(
                        "FilteredStates",
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._FilteredStates_Stub,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._FilteredStates_ComputeIsReadOnly,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._FilteredStates_Validate,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._FilteredStates_GetImplementationValue,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._FilteredStates_SetImplementationValue,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._FilteredStates_OnValueChanged);
                private static void _FilteredStates_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d, object sf)
                {
                    c(d, ref d._FilteredStates, sf);
                }
                private static bool _FilteredStates_ComputeIsReadOnly(global::LightSwitchApplication.UserPostListFilterItem e)
                {
                    bool result = false;
                    e.FilteredStates_IsReadOnly(ref result);
                    return result;
                }
                private static void _FilteredStates_Validate(global::LightSwitchApplication.UserPostListFilterItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.FilteredStates_Validate(r);
                }
                private static string _FilteredStates_GetImplementationValue(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d)
                {
                    return d.ImplementationEntity.FilteredStates;
                }
                private static void _FilteredStates_SetImplementationValue(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.FilteredStates = v;
                }
                private static void _FilteredStates_OnValueChanged(global::LightSwitchApplication.UserPostListFilterItem e)
                {
                    e.FilteredStates_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, string>.Entry
                    FilteredCountries = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, string>.Entry(
                        "FilteredCountries",
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._FilteredCountries_Stub,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._FilteredCountries_ComputeIsReadOnly,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._FilteredCountries_Validate,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._FilteredCountries_GetImplementationValue,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._FilteredCountries_SetImplementationValue,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._FilteredCountries_OnValueChanged);
                private static void _FilteredCountries_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d, object sf)
                {
                    c(d, ref d._FilteredCountries, sf);
                }
                private static bool _FilteredCountries_ComputeIsReadOnly(global::LightSwitchApplication.UserPostListFilterItem e)
                {
                    bool result = false;
                    e.FilteredCountries_IsReadOnly(ref result);
                    return result;
                }
                private static void _FilteredCountries_Validate(global::LightSwitchApplication.UserPostListFilterItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.FilteredCountries_Validate(r);
                }
                private static string _FilteredCountries_GetImplementationValue(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d)
                {
                    return d.ImplementationEntity.FilteredCountries;
                }
                private static void _FilteredCountries_SetImplementationValue(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.FilteredCountries = v;
                }
                private static void _FilteredCountries_OnValueChanged(global::LightSwitchApplication.UserPostListFilterItem e)
                {
                    e.FilteredCountries_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, bool>.Entry
                    ShowResponded = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, bool>.Entry(
                        "ShowResponded",
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._ShowResponded_Stub,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._ShowResponded_ComputeIsReadOnly,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._ShowResponded_Validate,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._ShowResponded_GetImplementationValue,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._ShowResponded_SetImplementationValue,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._ShowResponded_OnValueChanged);
                private static void _ShowResponded_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, bool>.Data> c, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d, object sf)
                {
                    c(d, ref d._ShowResponded, sf);
                }
                private static bool _ShowResponded_ComputeIsReadOnly(global::LightSwitchApplication.UserPostListFilterItem e)
                {
                    bool result = false;
                    e.ShowResponded_IsReadOnly(ref result);
                    return result;
                }
                private static void _ShowResponded_Validate(global::LightSwitchApplication.UserPostListFilterItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ShowResponded_Validate(r);
                }
                private static bool _ShowResponded_GetImplementationValue(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d)
                {
                    return d.ImplementationEntity.ShowResponded;
                }
                private static void _ShowResponded_SetImplementationValue(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d, bool v)
                {
                    d.ImplementationEntity.ShowResponded = v;
                }
                private static void _ShowResponded_OnValueChanged(global::LightSwitchApplication.UserPostListFilterItem e)
                {
                    e.ShowResponded_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, bool>.Entry
                    ShowNotResponded = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, bool>.Entry(
                        "ShowNotResponded",
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._ShowNotResponded_Stub,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._ShowNotResponded_ComputeIsReadOnly,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._ShowNotResponded_Validate,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._ShowNotResponded_GetImplementationValue,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._ShowNotResponded_SetImplementationValue,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._ShowNotResponded_OnValueChanged);
                private static void _ShowNotResponded_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, bool>.Data> c, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d, object sf)
                {
                    c(d, ref d._ShowNotResponded, sf);
                }
                private static bool _ShowNotResponded_ComputeIsReadOnly(global::LightSwitchApplication.UserPostListFilterItem e)
                {
                    bool result = false;
                    e.ShowNotResponded_IsReadOnly(ref result);
                    return result;
                }
                private static void _ShowNotResponded_Validate(global::LightSwitchApplication.UserPostListFilterItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ShowNotResponded_Validate(r);
                }
                private static bool _ShowNotResponded_GetImplementationValue(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d)
                {
                    return d.ImplementationEntity.ShowNotResponded;
                }
                private static void _ShowNotResponded_SetImplementationValue(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d, bool v)
                {
                    d.ImplementationEntity.ShowNotResponded = v;
                }
                private static void _ShowNotResponded_OnValueChanged(global::LightSwitchApplication.UserPostListFilterItem e)
                {
                    e.ShowNotResponded_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, bool>.Entry
                    FiltersEnabled = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, bool>.Entry(
                        "FiltersEnabled",
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._FiltersEnabled_Stub,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._FiltersEnabled_ComputeIsReadOnly,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._FiltersEnabled_Validate,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._FiltersEnabled_GetImplementationValue,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._FiltersEnabled_SetImplementationValue,
                        global::LightSwitchApplication.UserPostListFilterItem.DetailsClass.PropertySetProperties._FiltersEnabled_OnValueChanged);
                private static void _FiltersEnabled_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, bool>.Data> c, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d, object sf)
                {
                    c(d, ref d._FiltersEnabled, sf);
                }
                private static bool _FiltersEnabled_ComputeIsReadOnly(global::LightSwitchApplication.UserPostListFilterItem e)
                {
                    bool result = false;
                    e.FiltersEnabled_IsReadOnly(ref result);
                    return result;
                }
                private static void _FiltersEnabled_Validate(global::LightSwitchApplication.UserPostListFilterItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.FiltersEnabled_Validate(r);
                }
                private static bool _FiltersEnabled_GetImplementationValue(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d)
                {
                    return d.ImplementationEntity.FiltersEnabled;
                }
                private static void _FiltersEnabled_SetImplementationValue(global::LightSwitchApplication.UserPostListFilterItem.DetailsClass d, bool v)
                {
                    d.ImplementationEntity.FiltersEnabled = v;
                }
                private static void _FiltersEnabled_OnValueChanged(global::LightSwitchApplication.UserPostListFilterItem e)
                {
                    e.FiltersEnabled_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::System.Guid>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::System.Guid>.Data _UserId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _PostStartDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _PostEndDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _ResponseStartDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _ResponseEndDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, string>.Data _FilteredKeywords;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, string>.Data _FilteredCities;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, string>.Data _FilteredStates;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, string>.Data _FilteredCountries;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, bool>.Data _ShowResponded;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, bool>.Data _ShowNotResponded;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserPostListFilterItem, global::LightSwitchApplication.UserPostListFilterItem.DetailsClass, bool>.Data _FiltersEnabled;
            
        }
    
        #endregion
    }
    
    #endregion
}
